version: '3.8'
services:
  app:
    image: myapp:latest # Spring Boot 애플리케이션 Docker 이미지
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ballbin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hun380638@@
    ports:
      - "8080:8080" # 호스트의 8080 포트를 컨테이너의 8080 포트에 연결
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgresql:17.2
    container_name: postgres-container
    environment:
      POSTGRES_DB: ballbin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hun380638@@
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
